#!/bin/bash

if [ "$#" = "0" ]; then
	echo "Please provide atleast 1 argument"
	exit 1
fi

for argument in "$@" ; do
	echo -e "\n*********Compiling $argument **************"
	gcc -Wall -pedantic -Werror -Wextra -std=gnu89 "$argument"
	echo -e "\n*********Compiled successfully***"
done
